/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CargaGlnWallMart.java
 *
 * Created on 17/06/2011, 01:50:59 PM
 */
package gui;

import java.lang.String;
import catalogos.EntregasWallMart;
import dao.DaoEntregasWallMart;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;

/**
 *
 * @author carlosp
 */
public class CargaGlnWallMart extends javax.swing.JFrame {

    public static HashSet gln = new HashSet();
    EntregasWallMart entregasWallMart;
    private JMenuBar menuSea;

    /** Creates new form CargaGlnWallMart */
    public CargaGlnWallMart(JMenuBar jMenuBarSea) {
        initComponents();
        menuSea = jMenuBarSea;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCarga = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carga de GLNs Wallmart-Aurrera");
        setBackground(new java.awt.Color(204, 64, 99));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonCarga.setFont(new java.awt.Font("Arial", 0, 11));
        jButtonCarga.setText("Carga Datos de Hoja de Excel");
        jButtonCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargaActionPerformed(evt);
            }
        });

        jTextPane1.setContentType("");
        jTextPane1.setEditable(false);
        jTextPane1.setFont(new java.awt.Font("Arial", 0, 12));
        jTextPane1.setText("El archivo a importar debe de tener el nombre: MX_ESP_stores.xls\n\nEn la carpeta \\app\\pedidos");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(191, Short.MAX_VALUE)
                .addComponent(jButtonCarga)
                .addGap(129, 129, 129))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(151, 151, 151)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(139, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jButtonCarga)
                .addGap(110, 110, 110))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(68, 68, 68)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(155, Short.MAX_VALUE)))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargaActionPerformed
        //jMenuBarSea.setVisible(false);
        //gln = null;
        try {
            Workbook workbook = null;
            try {
                workbook = Workbook.getWorkbook(new File("MX_ESP_stores.xls"));
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "El archivo MX_ESP_stores.xls no se pudo abrir", "Aviso",
                        JOptionPane.ERROR_MESSAGE);

                //Logger.getLogger(CargaGlnWallMart.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BiffException ex) {
                Logger.getLogger(CargaGlnWallMart.class.getName()).log(Level.SEVERE, null, ex);
            }
            //Se obtiene la segunda hoja
            Sheet sheet = workbook.getSheet(2);
            int totFilas;
            totFilas = sheet.getRows();
            System.out.println(totFilas);
            for (int fila = 4; fila < totFilas; fila++) {
                entregasWallMart = new EntregasWallMart();
                Cell cellTda = sheet.getCell(1, fila);
                Cell cellGln = sheet.getCell(2, fila);
                entregasWallMart.setIdTienda(cellTda.getContents());
                entregasWallMart.setIdGln(cellGln.getContents());
                gln.add(entregasWallMart);
                //System.out.println(entregasWallMart);
            }
            DaoEntregasWallMart.escribeEntregasWallMart(gln);
            gln.removeAll(gln);
        } catch (SQLException ex) {
            Logger.getLogger(CargaGlnWallMart.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCargaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        menuSea.setVisible(true);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_formWindowClosing
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCarga;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
