/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CargaPedAuto.java
 *
 * Created on 30-jun-2012, 20:52:51
 */
package gui;

import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import dao.ErrorTransaccion;
import java.sql.SQLException;

import catalogos.BancosClientes;
import catalogos.MetodosPago;
import catalogos.Empresa;
import catalogos.Grupo;
import catalogos.GruposCuentas;
import controladores.ControladorEmpresa;
import controladores.ControladorGuardar;
import dao.DaoEmpresa;
import dao.ErrorTransaccion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenuBar;
import javax.swing.WindowConstants;

/**
 *
 * @author carlosp
 */
public class CargaPedAuto extends javax.swing.JFrame {

    private ControladorEmpresa controladorEmpresa;
    private JMenuBar menuSea;

    /** Creates new form CargaPedAuto */
    public CargaPedAuto(JMenuBar jMenuBarSea) throws ErrorTransaccion, SQLException {
        initComponents();
        menuSea = jMenuBarSea;
        cargaEmpresas(DaoEmpresa.leeTablaEmpresa());
        cargaGrupos(DaoEmpresa.leeTablaGrupo());
        cargaMetodos(DaoEmpresa.leeTablaMetodos());
        //cargaCuentas(DaoEmpresa.leeTablaCuentas());

    }

//    CargaPedAuto(JMenuBar jMenuBarSea) {
//        throw new UnsupportedOperationException("Not yet implemented");
//    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaGrupo = new javax.swing.JLabel();
        etiquetaEmpresa = new javax.swing.JLabel();
        botonImportarArchivo = new javax.swing.JButton();
        comboGrupo = new javax.swing.JComboBox();
        comboEmpresa = new javax.swing.JComboBox();
        comboMetodo = new javax.swing.JComboBox();
        comboCuenta = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        etiquetaGrupo.setText("Grupo:");

        etiquetaEmpresa.setText("Empresa:");

        botonImportarArchivo.setText("Importar Archivos");
        botonImportarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImportarArchivoActionPerformed(evt);
            }
        });

        comboGrupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                comboGrupoFocusLost(evt);
            }
        });

        comboEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEmpresaActionPerformed(evt);
            }
        });

        jLabel1.setText("Método Pago:");

        jLabel2.setText("Cuenta Pago:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboMetodo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonImportarArchivo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiquetaEmpresa)
                            .addComponent(etiquetaGrupo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboGrupo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboEmpresa, 0, 267, Short.MAX_VALUE))))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaGrupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(comboMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(comboCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(botonImportarArchivo)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonImportarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImportarArchivoActionPerformed
        // TODO add your handling code here:
        controladorEmpresa = new ControladorEmpresa(comboEmpresa, comboGrupo,comboMetodo,comboCuenta);
        botonImportarArchivo.addActionListener(controladorEmpresa);
    }//GEN-LAST:event_botonImportarArchivoActionPerformed

    private void comboEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEmpresaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_comboEmpresaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        menuSea.setVisible(true);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_formWindowClosing

    private void comboGrupoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_comboGrupoFocusLost
        // TODO add your handling code here:
        Grupo gc = (Grupo)comboGrupo.getSelectedItem();
        //int codgru = Integer.parseInt(gc.getCod_gru());
        try {
            cargaCuentas(DaoEmpresa.leeTablaCuentas(Integer.parseInt(gc.getCod_gru())));
        } catch (ErrorTransaccion ex) {
            Logger.getLogger(CargaPedAuto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(CargaPedAuto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboGrupoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonImportarArchivo;
    private static javax.swing.JComboBox comboCuenta;
    private static javax.swing.JComboBox comboEmpresa;
    private static javax.swing.JComboBox comboGrupo;
    private static javax.swing.JComboBox comboMetodo;
    private javax.swing.JLabel etiquetaEmpresa;
    private javax.swing.JLabel etiquetaGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private static void cargaEmpresas(ArrayList lista) {
        java.util.Iterator it = lista.iterator();
        while (it.hasNext()) {
            {
                Empresa empresa = (Empresa) it.next();
                comboEmpresa.addItem(empresa);
            }
        }
    }

    private static void cargaGrupos(ArrayList lBodega) {
        java.util.Iterator it = lBodega.iterator();
        while (it.hasNext()) {
            Grupo grupo = (Grupo) it.next();
            comboGrupo.addItem(grupo);
        }
    }


    private static void cargaMetodos(ArrayList arregloMetodos) {
        java.util.Iterator it = arregloMetodos.iterator();
        while (it.hasNext()) {
            MetodosPago mp = (MetodosPago) it.next();
            comboMetodo.addItem(mp);
        }
    }

    private void cargaCuentas(ArrayList arregloCtasBcos) {
        comboCuenta.removeAllItems();
        java.util.Iterator it = arregloCtasBcos.iterator();
        while (it.hasNext()) {
            GruposCuentas gc = (GruposCuentas) it.next();
            System.out.println("cargando tabla de cuentas bancarias "+gc.getIdBanco());
            comboCuenta.addItem(gc);
        }
    }
}