/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CargaBancos.java
 *
 * Created on 01-mar-2012, 10:17:24
 */
package gui;

import catalogos.BancosClientes;
import catalogos.BancosSat;
import catalogos.Cliente;
import catalogos.Direccion;
import dao.DaoBancosSat;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JMenuBar;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.read.biff.BiffException;
import utilerias.FiltroArchivos;

/**
 *
 * @author carlosp
 */
public class CargaBancos extends javax.swing.JFrame {

    public static HashSet bco = new HashSet();
    public static HashMap bcos = new HashMap();
    public static ArrayList ctesBcos = new ArrayList();
    public static ArrayList gposCtes = new ArrayList();
    BancosSat bancosSat;
    BancosClientes bancosClientes;
    //BancosClientes bancosGrupos;
    private JMenuBar menuSea;
    Sheet hoja;

    /** Creates new form CargaBancos */
    public CargaBancos(JMenuBar jMenuBarSea) throws SQLException {
        bcos = dao.DaoBancosSat.leeBancosSat();
        initComponents();
        menuSea = jMenuBarSea;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCargaBcos = new javax.swing.JButton();
        jButtonCtesBcos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonGposCtes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jButtonCargaBcos.setText("Carga Bancos");
        jButtonCargaBcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargaBcosActionPerformed(evt);
            }
        });

        jButtonCtesBcos.setText("Carga Clientes-Bancos");
        jButtonCtesBcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCtesBcosActionPerformed(evt);
            }
        });

        jButton2.setText("Prueba Direcciones");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonGposCtes.setText("Carga Grupos-Bancos");
        jButtonGposCtes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGposCtesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(282, Short.MAX_VALUE)
                .addComponent(jButtonCargaBcos)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGposCtes)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCtesBcos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButtonCargaBcos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCtesBcos)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGposCtes)
                .addContainerGap(194, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargaBcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargaBcosActionPerformed
        try {
            // TODO add your handling code here:
            // try {
            Workbook workbook = null;
            try {
                workbook = Workbook.getWorkbook(new File("e:/desarrolloJava/sat/catalogoDeBancos.xls"));
            } catch (BiffException ex) {
                Logger.getLogger(CargaBancos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                System.out.println("Error leyendo archivo de bancos");
            }
            Sheet sheet = workbook.getSheet(0);
            int totFilas;
            totFilas = sheet.getRows();
            System.out.println(totFilas);
            for (int fila = 2; fila < totFilas; fila++) {
                bancosSat = new BancosSat();
                Cell cellCve = sheet.getCell(0, fila);
                Cell cellRfc = sheet.getCell(1, fila);
                Cell cellRazon = sheet.getCell(2, fila);
                Cell cellNombre = sheet.getCell(3, fila);
                bancosSat.setCodigoBanco(Integer.parseInt(cellCve.getContents()));
                bancosSat.setRfc(cellRfc.getContents());
                bancosSat.setRazonSocial(cellRazon.getContents());
                bancosSat.setNombreCorto(cellNombre.getContents());
                bco.add(bancosSat);
                System.out.println("datos a guardar " + bancosSat);
            }
            DaoBancosSat.escribeBancosSat(bco);
        } catch (SQLException ex) {
            Logger.getLogger(CargaBancos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCargaBcosActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        menuSea.setVisible(true);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_formWindowClosing

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Direccion d = new Direccion();
        d.setCalle("69-A");
        d.setNumeroExterior("275");
        d.setNumeroInterior("ninguno");
        d.setColonia("Fracc. Bosques del poniente");
        d.setLocalidad("Merida");
        d.setReferencia("a una esquna de mercado soriana");
        d.setMunicipio("Merida");
        d.setEstado("Yucatan");
        d.setIdPais(1);
        d.setCodigoPostal("97246");
        d.setNumeroLocalizacion("1234567890123");
        System.out.println(d);
        try {
            dao.DaoBancosSat.agregarDireccion(d);
        } catch (SQLException ex) {
            Logger.getLogger(CargaBancos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CargaBancos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonCtesBcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCtesBcosActionPerformed
        // TODO add your handling code here:
        Sheet hoja = leeHojaCalculo();
        int totFilas;
        totFilas = hoja.getRows();
        for (int fila = 1; fila < totFilas; fila++) {
            bancosClientes = new BancosClientes();
            Cell cellCte = hoja.getCell(0, fila);
            Cell cellBco = hoja.getCell(2, fila);
            Cell cellCta = hoja.getCell(3, fila);
            Cell cellMetodo = hoja.getCell(4, fila);
            bancosClientes.setCodigoCliente(cellCte.getContents());
            try {
                bancosClientes.setIdBanco(Integer.parseInt(cellBco.getContents()));
            } catch (NumberFormatException e) {
                bancosClientes.setIdBanco(0);
            }
            bancosClientes.setNumCtaPago(cellCta.getContents());
            bancosClientes.setMedioPago(cellMetodo.getContents());
            ctesBcos.add(bancosClientes);
        }
        try {
            DaoBancosSat.escribeBancosClientes(ctesBcos, bcos);
        } catch (SQLException ex) {
            Logger.getLogger(CargaBancos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButtonCtesBcosActionPerformed
    private void jButtonGposCtesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGposCtesActionPerformed
        // TODO add your handling code here:
        Sheet hoja = leeHojaCalculo();
        int totFilas;
        totFilas = hoja.getRows();
        for (int fila = 1; fila < totFilas; fila++) {
            bancosClientes = new BancosClientes();
            Cell cellGpo = hoja.getCell(0, fila);
            Cell cellBco = hoja.getCell(3, fila);
            Cell cellCta = hoja.getCell(4, fila);
            Cell cellMetodo = hoja.getCell(5, fila);
            bancosClientes.setCodigoCliente(cellGpo.getContents());
            try {
                bancosClientes.setIdBanco(Integer.parseInt(cellBco.getContents()));
            } catch (NumberFormatException e) {
                bancosClientes.setIdBanco(0);
            }
            bancosClientes.setNumCtaPago(cellCta.getContents());
            bancosClientes.setMedioPago(cellMetodo.getContents());
            ctesBcos.add(bancosClientes);
            System.out.println("datos a guardar " + bancosClientes);
        }
        try {
            DaoBancosSat.escribeBancosGrupos(ctesBcos, bcos);
        } catch (SQLException ex) {
            Logger.getLogger(CargaBancos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonGposCtesActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
            }
        });
    }

    private Sheet leeHojaCalculo() {
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de Excel", "xls");
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(filtro);
        int resultArch = fileChooser.showDialog(jButtonGposCtes, "Cargar Archivo");
        if (resultArch == JFileChooser.APPROVE_OPTION) {
            File archivoCtes = fileChooser.getSelectedFile();
            Workbook workbook = null;
            try {
                workbook = Workbook.getWorkbook(archivoCtes);
            } catch (BiffException ex) {
                Logger.getLogger(CargaBancos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                System.out.println("Error leyendo archivo de grupos");
            }
            hoja = workbook.getSheet(0);
        }
        return hoja;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCargaBcos;
    private javax.swing.JButton jButtonCtesBcos;
    private javax.swing.JButton jButtonGposCtes;
    // End of variables declaration//GEN-END:variables
}
