/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MenuNbPedidos.java
 *
 * Created on 17/06/2011, 12:06:27 PM
 */
package gui;

import controladores.ControladorConexion;
import dao.ErrorTransaccion;
import gui.CargaGlnWallMart;
import gui.CargaPedAuto;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author carlosp
 */
public class MenuNbPedidos extends javax.swing.JFrame {

    //private ControladorConexion controladorConexion;

    /** Creates new form MenuNbPedidos */
    public MenuNbPedidos() {
        //ImageIcon imagenFondo = new ImageIcon(getClass().getResource("/imagenes/logo_grupo_anita.jpg")); 
        initComponents();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAccesoBd = new javax.swing.JPanel();
        jButtonAceptar = new javax.swing.JButton();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContrasenia = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jPasswordContrasenia = new javax.swing.JPasswordField();
        jMenuBarSea = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuCargaGlns = new javax.swing.JMenuItem();
        jMenuEmpaques = new javax.swing.JMenuItem();
        jMenuBancosSat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuOrdenesCompra = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuCuentasxCobrar = new javax.swing.JMenu();
        jMenuReportes = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Sistema Empresarial Anita");
        setBackground(new java.awt.Color(255, 0, 102));
        setFont(new java.awt.Font("Arial", 0, 14));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanelAccesoBd.setBackground(new java.awt.Color(204, 204, 255));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jLabelUsuario.setText("Id de inicio de sesión:");

        jLabelContrasenia.setText("Contraseña:");

        javax.swing.GroupLayout jPanelAccesoBdLayout = new javax.swing.GroupLayout(jPanelAccesoBd);
        jPanelAccesoBd.setLayout(jPanelAccesoBdLayout);
        jPanelAccesoBdLayout.setHorizontalGroup(
            jPanelAccesoBdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAccesoBdLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanelAccesoBdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelContrasenia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUsuario, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAccesoBdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAccesoBdLayout.createSequentialGroup()
                        .addComponent(jPasswordContrasenia, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addContainerGap(48, Short.MAX_VALUE))
                    .addGroup(jPanelAccesoBdLayout.createSequentialGroup()
                        .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAccesoBdLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(jButtonAceptar)
                .addGap(123, 123, 123))
        );
        jPanelAccesoBdLayout.setVerticalGroup(
            jPanelAccesoBdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAccesoBdLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(jPanelAccesoBdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsuario)
                    .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAccesoBdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordContrasenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContrasenia))
                .addGap(18, 18, 18)
                .addComponent(jButtonAceptar)
                .addGap(17, 17, 17))
        );

        jMenuBarSea.setBackground(new java.awt.Color(204, 204, 204));

        jMenu1.setText("Catálogos");

        jMenuCargaGlns.setText("Carga GLNs Wallmart");
        jMenuCargaGlns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCargaGlnsActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCargaGlns);

        jMenuEmpaques.setText("Empaques");
        jMenuEmpaques.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEmpaquesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuEmpaques);

        jMenuBancosSat.setText("Bancos Sat");
        jMenuBancosSat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBancosSatActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuBancosSat);

        jMenuBarSea.add(jMenu1);

        jMenu2.setText("Ventas");

        jMenuOrdenesCompra.setText("Ordenes de Compra Autoservicios");
        jMenuOrdenesCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOrdenesCompraActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuOrdenesCompra);

        jMenuItem2.setText("Captura de Gastos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBarSea.add(jMenu2);

        jMenuCuentasxCobrar.setText("Cuentas x Cobrar");

        jMenuReportes.setText("Reportes");
        jMenuReportes.setToolTipText("");
        jMenuReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReportesActionPerformed(evt);
            }
        });
        jMenuCuentasxCobrar.add(jMenuReportes);

        jMenuBarSea.add(jMenuCuentasxCobrar);

        setJMenuBar(jMenuBarSea);
        jMenuBarSea.getAccessibleContext().setAccessibleParent(jPanelAccesoBd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(399, 399, 399)
                .addComponent(jPanelAccesoBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(jPanelAccesoBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        controladorConexion = new ControladorConexion(jTextUsuario, jPasswordContrasenia, jPanelAccesoBd, jMenuBarSea);
        jButtonAceptar.addActionListener(controladorConexion);
	    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jMenuOrdenesCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOrdenesCompraActionPerformed
        //jMenuBarSea.setVisible(false);
        //CargaPed cargaPed = null;
        CargaPedAuto cargaPedAuto = null;
        try {
            cargaPedAuto = new CargaPedAuto(jMenuBarSea);
        } catch (ErrorTransaccion ex) {
            Logger.getLogger(MenuNbPedidos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuNbPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        jMenuBarSea.setVisible(false);
        cargaPedAuto.setVisible(true);
    }//GEN-LAST:event_jMenuOrdenesCompraActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Desea Salir del Sistema?",
                "Confirmacion", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirmacion == JOptionPane.OK_OPTION) {
            setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        }
        System.out.println(confirmacion);
    }//GEN-LAST:event_formWindowClosing

    private void jMenuCargaGlnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCargaGlnsActionPerformed
        CargaGlnWallMart cargaGlnWallMart = new CargaGlnWallMart(jMenuBarSea);
        jMenuBarSea.setVisible(false);
        cargaGlnWallMart.setVisible(true);
    }//GEN-LAST:event_jMenuCargaGlnsActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CapturaGastos capturaGastos = null;
        try {
            try {
                capturaGastos = new CapturaGastos(jMenuBarSea);
            } catch (ErrorTransaccion ex) {
                Logger.getLogger(MenuNbPedidos.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error en carga de formulario", "Aviso",
                    JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(MenuNbPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        jMenuBarSea.setVisible(false);
        capturaGastos.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuEmpaquesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEmpaquesActionPerformed
        try {
            // TODO add your handling code here:
            CatalogoEmpaques catalogoEmpaques = null;
            try {
                catalogoEmpaques = new CatalogoEmpaques(jMenuBarSea);
            } catch (SQLException ex) {
                Logger.getLogger(MenuNbPedidos.class.getName()).log(Level.SEVERE, null, ex);
            }
            jMenuBarSea.setVisible(false);
            catalogoEmpaques.setVisible(true);
        } catch (ErrorTransaccion ex) {
            Logger.getLogger(MenuNbPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuEmpaquesActionPerformed

    private void jMenuReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReportesActionPerformed
        // TODO add your handling code here:
        ReportesCxc reportesCxc = null;
        try {
            reportesCxc = new ReportesCxc(jMenuBarSea);
        } catch (ErrorTransaccion ex) {
            Logger.getLogger(MenuNbPedidos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MenuNbPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        jMenuBarSea.setVisible(false);
        reportesCxc.setVisible(true);

    }//GEN-LAST:event_jMenuReportesActionPerformed

    private void jMenuBancosSatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBancosSatActionPerformed
        // TODO add your handling code here:
        CargaBancos cargaBancos = null;
        try {
            cargaBancos = new CargaBancos(jMenuBarSea);
        } catch (SQLException ex) {
            Logger.getLogger(MenuNbPedidos.class.getName()).log(Level.SEVERE, null, ex);
        }
        jMenuBarSea.setVisible(false);
        cargaBancos.setVisible(true);
    }//GEN-LAST:event_jMenuBancosSatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuNbPedidos().setVisible(true);
                jMenuBarSea.setVisible(false);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuBancosSat;
    public static javax.swing.JMenuBar jMenuBarSea;
    private javax.swing.JMenuItem jMenuCargaGlns;
    private javax.swing.JMenu jMenuCuentasxCobrar;
    private javax.swing.JMenuItem jMenuEmpaques;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuOrdenesCompra;
    private javax.swing.JMenuItem jMenuReportes;
    private javax.swing.JPanel jPanelAccesoBd;
    private javax.swing.JPasswordField jPasswordContrasenia;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
    private ControladorConexion controladorConexion;
}
