/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportesCxc.java
 *
 * Created on 28/07/2011, 11:27:10 AM
 */
package gui;

import catalogos.Empresa;
import catalogos.Grupo;
import controladores.GeneraReportes;
import dao.DaoEmpresa;
import dao.DaoVentas;
import dao.ErrorTransaccion;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JMenuBar;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import validaCatalogos.ConsultaCanceladas;
import validaCatalogos.ConsultaSaldoGrupo;

/**
 *
 * @author carlosp
 */
public class ReportesCxc extends javax.swing.JFrame {

    private GeneraReportes generaReportes;
    private JMenuBar menuSea;
    public ArrayList aSdos;
    public ArrayList aCance;
    private String fechaInicial;
    private String fechaFinal;

    /** Creates new form ReportesCxc */
    public ReportesCxc(JMenuBar jMenuBarSea) throws ErrorTransaccion, SQLException {
        menuSea = jMenuBarSea;
        initComponents();
        cargaEmpresas(DaoEmpresa.leeTablaEmpresa());
        cargaBodegas(DaoEmpresa.leeTablaGrupo());
    }

    private ReportesCxc() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelEmpresa = new javax.swing.JLabel();
        jComboGrupo = new javax.swing.JComboBox();
        jLabelGrupo1 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        jRadioSaldos = new javax.swing.JRadioButton();
        jRadioCanceladas = new javax.swing.JRadioButton();
        jComboEmpresa = new javax.swing.JComboBox();
        jToolBar1 = new javax.swing.JToolBar();
        jButtonGenera = new javax.swing.JButton();
        jButtonDeshacer = new javax.swing.JButton();
        jButtonExcel = new javax.swing.JButton();
        jButtonPrevio = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reportes Cuentas x Cobrar");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelEmpresa.setText("Empresa:");

        jComboGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboGrupoActionPerformed(evt);
            }
        });

        jLabelGrupo1.setText("Grupo:");

        buttonGroup1.add(jRadioSaldos);
        jRadioSaldos.setText("Saldos Pendientes");
        jRadioSaldos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioSaldosActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioCanceladas);
        jRadioCanceladas.setText("Canceladas Mismo Mes");
        jRadioCanceladas.setActionCommand("");

        jToolBar1.setRollover(true);

        jButtonGenera.setIcon(new javax.swing.ImageIcon("E:\\proyNetBeans\\iconos\\copy.gif")); // NOI18N
        jButtonGenera.setToolTipText("Genera Reporte");
        jButtonGenera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeneraActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonGenera);

        jButtonDeshacer.setIcon(new javax.swing.ImageIcon("E:\\proyNetBeans\\iconos\\undo_edit.gif")); // NOI18N
        jButtonDeshacer.setToolTipText("Deshacer");
        jButtonDeshacer.setEnabled(false);
        jButtonDeshacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeshacerActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonDeshacer);

        jButtonExcel.setIcon(new javax.swing.ImageIcon("E:\\proyNetBeans\\iconos\\prop_ps.gif")); // NOI18N
        jButtonExcel.setToolTipText("Exportar Archivo a Excel");
        jButtonExcel.setEnabled(false);
        jButtonExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcelActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonExcel);

        jButtonPrevio.setIcon(new javax.swing.ImageIcon("E:\\proyNetBeans\\iconos\\review_ccs_task.gif")); // NOI18N
        jButtonPrevio.setToolTipText("Vista Preliminar");
        jButtonPrevio.setEnabled(false);
        jButtonPrevio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrevioActionPerformed(evt);
            }
        });
        jToolBar1.add(jButtonPrevio);

        jButton1.setText("jButton1");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelEmpresa)
                    .addComponent(jLabelGrupo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(267, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioSaldos)
                            .addComponent(jRadioCanceladas))))
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(153, 153, 153))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEmpresa)
                            .addComponent(jComboEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGrupo1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateChooserCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(jRadioSaldos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioCanceladas))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(142, 142, 142))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGeneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeneraActionPerformed
        // TODO add your handling code here:
        Date fechIni = dateChooserCombo1.getCurrent().getTime();
        Date fechFin = dateChooserCombo2.getCurrent().getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        fechaInicial = sdf.format(fechIni);
        fechaFinal = sdf.format(fechFin);
        if (jRadioSaldos.isSelected()) {
            try {
                aSdos = GeneraReportes.devuelveConsulta(jComboEmpresa, jComboGrupo, fechaInicial, fechaFinal);
                JOptionPane.showMessageDialog(null, "Proceso de Generación Concluido", "Aviso",
                        JOptionPane.INFORMATION_MESSAGE);
                jButtonExcel.setEnabled(true);
                jButtonDeshacer.setEnabled(true);
                jButtonGenera.setEnabled(false);
                jComboEmpresa.setEnabled(false);
                jComboGrupo.setEnabled(false);
                dateChooserCombo1.setEnabled(false);
                dateChooserCombo2.setEnabled(false);
            } catch (ErrorTransaccion ex) {
                Logger.getLogger(ReportesCxc.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ReportesCxc.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ReportesCxc.class.getName()).log(Level.SEVERE, null, ex);
            }
            System.out.println("se genera reporte de saldos");

        } else if (jRadioCanceladas.isSelected()) {
            try {
                aCance = GeneraReportes.consultaCanceMismoMes(jComboEmpresa, jComboGrupo, fechaInicial, fechaFinal);
                JOptionPane.showMessageDialog(null, "Proceso de Generación Concluido", "Aviso",
                        JOptionPane.INFORMATION_MESSAGE);
                jButtonPrevio.setEnabled(true);
                jButtonExcel.setEnabled(true);
                jButtonDeshacer.setEnabled(true);
                jButtonGenera.setEnabled(false);
                jComboEmpresa.setEnabled(false);
                jComboGrupo.setEnabled(false);
                dateChooserCombo1.setEnabled(false);
                dateChooserCombo2.setEnabled(false);

            } catch (ErrorTransaccion ex) {
                Logger.getLogger(ReportesCxc.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(ReportesCxc.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ReportesCxc.class.getName()).log(Level.SEVERE, null, ex);
            }
            //System.out.println("se genera reporte de facturas canceladas");
        }
    }//GEN-LAST:event_jButtonGeneraActionPerformed

    private void jButtonExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcelActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int resultado = fileChooser.showSaveDialog(this);
        if (resultado == fileChooser.CANCEL_OPTION) {
            return;
        }
        File archivo = fileChooser.getSelectedFile();
        if (jRadioSaldos.isSelected()) {
            try {
                PrintWriter salida = new PrintWriter(new FileWriter(archivo + ".csv"));
                salida.print("Cliente,No. Tienda,O.Compra,Bodega,No. Factura,Fecha Fac.,Importe,Saldo,");
                salida.println();
                String data[][] = obtenerInformacion();
                for (int i = 0; i < data.length; i++) {
                    salida.print(data[i][0]);
                    for (int j = 1; j < data[i].length; j++) {
                        String word = data[i][j];
                        if (word != null) {
                            salida.print("," + word);
                        } else {
                            salida.print(",");
                        }
                    }
                    salida.println();
                }
                salida.close();
                JOptionPane.showMessageDialog(null, "Proceso de Exportación Concluido", "Aviso",
                        JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException io) {
            }
        } else if (jRadioCanceladas.isSelected()) {
            try {
                PrintWriter salida = new PrintWriter(new FileWriter(archivo + ".csv"));
                salida.println("Documento,Cliente,Agente,Fecha Doc.,Fecha Cancel,SubTotal,Descuento,I.V.A.,Total");
                String data[][] = GeneraReportes.obtenerInformacion(aCance);
                for (int i = 0; i < data.length; i++) {
                    salida.print(data[i][0]);
                    for (int j = 1; j < data[i].length; j++) {
                        String word = data[i][j];
                        if (word != null) {
                            salida.print("," + word);
                        } else {
                            salida.print(",");
                        }
                    }
                    salida.println();
                }
                salida.close();
                JOptionPane.showMessageDialog(null, "Proceso de Exportación Concluido", "Aviso",
                        JOptionPane.INFORMATION_MESSAGE);

            } catch (IOException ex) {
                Logger.getLogger(ReportesCxc.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonExcelActionPerformed

    private void jComboGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboGrupoActionPerformed

    private void jButtonDeshacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeshacerActionPerformed
        // TODO add your handling code here:
        jButtonExcel.setEnabled(false);
        jButtonDeshacer.setEnabled(false);
        jButtonGenera.setEnabled(true);
        jComboEmpresa.setEnabled(true);
        jComboGrupo.setEnabled(true);
        dateChooserCombo1.setEnabled(true);
        dateChooserCombo2.setEnabled(true);
        jButtonPrevio.setEnabled(false);
    }//GEN-LAST:event_jButtonDeshacerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        menuSea.setVisible(true);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_formWindowClosing

    private void jButtonPrevioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrevioActionPerformed
        // TODO add your handling code here:
        //jButtonExcel.setEnabled(false);
        jButtonDeshacer.setEnabled(true);
        jButtonGenera.setEnabled(false);
        jComboEmpresa.setEnabled(false);
        jComboGrupo.setEnabled(false);
        dateChooserCombo1.setEnabled(false);
        dateChooserCombo2.setEnabled(false);
        jButtonPrevio.setEnabled(true);
        GeneraReportes.generaDocumento(aCance, jComboEmpresa, fechaInicial, fechaFinal);

    }//GEN-LAST:event_jButtonPrevioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Date fechIni = dateChooserCombo1.getCurrent().getTime();
        Date fechFin = dateChooserCombo2.getCurrent().getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        fechaInicial = sdf.format(fechIni);
        fechaFinal = sdf.format(fechFin);
        System.out.println(fechaInicial+" parametros "+fechaFinal);
        try {
            try {
                DaoVentas.leeVentas(fechaInicial, fechaFinal);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ReportesCxc.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ReportesCxc.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioSaldosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioSaldosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioSaldosActionPerformed

    public String[][] obtenerInformacion() {
        String matrix[][] = new String[aSdos.size()][8];
        for (int i = 0; i < aSdos.size(); i++) {
            ConsultaSaldoGrupo registro = (ConsultaSaldoGrupo) aSdos.get(i);
            matrix[i][0] = (String) (registro.getCod_cli().toString());
            matrix[i][1] = (String) (registro.getNumtda().toString());
            matrix[i][2] = (String) (registro.getPedido().toString());
            matrix[i][3] = (String) (registro.getCod_bod().toString());
            matrix[i][4] = (String) (registro.getCod_fac().toString());
            matrix[i][5] = (String) (registro.getFechapli().toString());
            matrix[i][6] = (String) (String.valueOf(registro.getImporte()));
            matrix[i][7] = (String) (String.valueOf(registro.getSaldo()));
        }
        return matrix;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //     try {
                new ReportesCxc().setVisible(true);
                //     } catch (SQLException ex) {
                //         Logger.getLogger(ReportesCxc.class.getName()).log(Level.SEVERE, null, ex);
                //     }
            }
        });
    }

    private static void cargaEmpresas(ArrayList lista) {
        java.util.Iterator it = lista.iterator();
        while (it.hasNext()) {
            {
                Empresa empresa = (Empresa) it.next();
                jComboEmpresa.addItem(empresa);
            }
        }
    }

    private static void cargaBodegas(ArrayList lBodega) {
        java.util.Iterator it = lBodega.iterator();
        while (it.hasNext()) {
            Grupo grupo = (Grupo) it.next();
            jComboGrupo.addItem(grupo);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDeshacer;
    private javax.swing.JButton jButtonExcel;
    private javax.swing.JButton jButtonGenera;
    private javax.swing.JButton jButtonPrevio;
    private static javax.swing.JComboBox jComboEmpresa;
    private static javax.swing.JComboBox jComboGrupo;
    private javax.swing.JLabel jLabelEmpresa;
    private javax.swing.JLabel jLabelGrupo1;
    private javax.swing.JRadioButton jRadioCanceladas;
    private javax.swing.JRadioButton jRadioSaldos;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
